
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =              36
     no. of nonzeroes in lower triangle of a =             378
     no. of nonzeroes in the factor l        =             724
     ratio of nonzeroes in factor (min/max)  =          0.1014
     number of super nodes                   =               3
     maximum order of a front matrix         =              18
     maximum size of a front matrix          =             171
     maximum size of a front trapezoid       =             171
     no. of floating point ops for factor    =      4.6860D+03
     no. of floating point ops for solve     =      2.0890D+03
     ratio of flops for factor (min/max)     =          0.1977
     ratio of allocated memory (max/min)     =          1.0022
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               3
     number of threads per process used      =               1
     number of cores used                    =               3
     time (cpu & wall) for structure input   =        0.000000        0.000040
     time (cpu & wall) for ordering          =        0.000000        0.001466
     time (cpu & wall) for other matrix prep =        0.000000        0.001866
     time (cpu & wall) for value input       =        0.000000        0.000017
     time (cpu & wall) for matrix distrib.   =        0.000000        0.003603

     no input or output performed

  Solver Memory allocated on core    0       =        0.214 MB
  Solver Memory allocated on core    1       =        0.215 MB
  Solver Memory allocated on core    2       =        0.214 MB
  Total Solver Memory allocated by all cores =        0.643 MB

